# Setup
title:                Learning-to-Hash
tagline:             'A Living Literature Review of Learning-to-Hash for Nearest Neighbour Search'
description:         'A webpage dedicated to the latest research on learning-to-hash, including state-of-the-art deep hashing models, all updated on a weekly basis. Maintained by [Sean Moran](http://sjmoran.github.io/)'
url:                 https://learning2hash.github.io
baseurl:             ''
disqus:
  shortname: sjmoran
collections:
  publications:
    output: true
    permalink: /:collection/:path/
future: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
