# Setup
title:                Awesome Learning to Hash
tagline:             'A Living Literature Review of Learning to Hash'
description:         'A Webpage dedicated to the latest research on Hash Function Learning. Maintained by <a href="http://sjmoran.github.io/">Sean Moran</a>.'
url:                 https://learning2hash.github.io
baseurl:             ''
disqus:
  shortname: sjmoran
collections:
  publications:
    output: true
    permalink: /:collection/:path/
future: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
